# Generated by Django 3.1.4 on 2021-06-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='phone',
            new_name='phoneNumber',
        ),
    ]
