# Generated by Django 3.1.4 on 2021-06-13 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rApi', '0002_auto_20210613_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='phoneNumber',
            new_name='phone',
        ),
    ]
