# Generated by Django 3.1.4 on 2021-06-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rApi', '0003_auto_20210613_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=60, null=True, unique=True, verbose_name='email'),
        ),
    ]
