# Generated by Django 3.1.4 on 2021-06-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rApi', '0004_auto_20210613_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
